"C:\Program Files (x86)\Python36-32\python.exe" C:/Users/medua/Dropbox/00Iniciode_Doctorado/Gits/diagnostic_data/Diagnostic_serial_only.py
Serial port: COM13, Baud rate:2000000
C>N>26>
M0;T340336805;
M0;T0;
P;T341336833;
P;T341336945;
N;T341336960;
N;T341337074;
R
M0;T0;
P;T343337113;
P;T343337325;
N;T343337341;
N;T343337553;
R
M0;T0;
P;T345337591;
P;T345337903;
N;T345337918;
N;T345338232;
R
M0;T0;
P;T347338270;
P;T347338682;
N;T347338698;
N;T347339112;
R
M0;T0;
P;T349339150;
P;T349339663;
N;T349339680;
N;T349340192;
R
M0;T0;
P;T351340231;
P;T351340844;
N;T351340859;
N;T351341472;
R
M0;T0;
P;T353341510;
P;T353342222;
N;T353342238;
N;T353342952;
R
M0;T0;
P;T355342988;
P;T355343801;
N;T355343816;
N;T355344629;
R
M0;T0;
P;T357344668;
P;T357345581;
N;T357345597;
N;T357346510;
R
M0;T359346540;
Terminou Captura

Process finished with exit code 0
